### ISSUE TITLE
Grid lines styles

### ISSUE THREAD

**Issue by bia-effcreativve** [ChartIQ/Charting-Library---AngularJS-Seed-Project#13]
Hello! How to configure grid lines styles, for example i want to make horizontal grid lines dotted?

![](https://w3tls.net/8M1Xouf0ee97231c07cdae002c166553a91292.png)

**Comment by NachoMoment** [comment]
Hi @bia-effcreativve! We are adding support for patterned gridlines with our next release, 3.1, which is due to be released on 6/30/17
For support with future library related questions feel free to send a support request to dev@chartiq.com

**Comment by bia-effcreativve** [comment]
@NachoMoment Thanks!
