### ISSUE TITLE
About inject

### ISSUE THREAD

**Issue by XueDong369** [ChartIQ/Charting-Library---AngularJS-Seed-Project#6]
For components, could you add the injector for every component before the callback?
For example, 'ThemeDialog.$inject = ['$scope', '$rootScope']';
Because when I try to build and compress the code, it will cause the error '$injector:unpr
Unknown Provider';
The solution is 'https://docs.angularjs.org/error/$injector/unpr?p0=aProvider%20%3C-%20a';
BTW, could you format all of codes before it push to github? So that, all of codes format are more structured.

**Comment by jaythomas** [comment]
@XueDong369 I have a pull request in to add  the injection, however I am not sure I understand your second request `BTW, could you format all of codes before it push to github?`.

**Comment by XueDong369** [comment]
I have commit format of codes for chartIQ, please could you review it?
